/**
 * Created by flynn on 23/07/17.
 */

// code to be run AFTER the wistia code has finished executing

(function(document, window){
        // get the actual video element

    function purgeBloatElements(){
        var styleElements = document.documentElement.getElementsByTagName('style'),
            iframeElements = document.documentElement.getElementsByTagName('iframe'),
            i = styleElements.length;

        console.log(styleElements)

        while (i--){
            // remove any bloat style elements generated by Wistia
            styleElements[i].parentNode.removeChild(styleElements[i]); // removeNode
        }

        i = iframeElements.length;

        while (i--){
            // remove any bloat iframes generated by Wistia
            iframeElements[i].parentNode.removeChild(iframeElements[i]); // removeNode
        }
    }

    // FOR DEV ONLY, sanitize the element and all of it's children containing "style" attributes
    function sanitizeInlineStyles(element){
        element.removeAttribute('style'); // remove style from the main element

        var styledChildren = element.querySelectorAll('*[style]'),
            i = styledChildren.length;

        while (i--){
            styledChildren[i].setAttribute('style', '');
        }
    }

    /*
    function clickOverride(e){
        e.preventDefault(); // prevent event doing anything else
        console.log('pressed!');
        return true;
    }

    // add overides to prevent fullscreening
    mainVideo.addEventListener('click', clickOverride, true);
    mainVideo.addEventListener('touchstart', clickOverride, true);
    mainVideo.addEventListener('touchend', clickOverride, true);
    */


   /* var loadDeferredStyles = function() {
        var addStylesNode = document.getElementById("deferred-styles");
        var replacement = document.createElement("div");
        replacement.innerHTML = addStylesNode.textContent;
        document.body.appendChild(replacement)
        addStylesNode.parentElement.removeChild(addStylesNode);
    };
*/

    var documentLoaded = false; // flag to be set if dom is loaded

    // code to be executed after the DOM has loaded
    function afterLoadEvent(){
        documentLoaded = true; // flag that the DOM is loaded and repeat executions are not needed

        var mainVideo = document.getElementsByClassName('main-video')[0]; // get the video container

        if (mainVideo){
            // force enable HTML5 video controls
            var videoElement = mainVideo.getElementsByTagName('video')[0];
            videoElement.setAttribute('controls', '');
        }
        console.log('Loading deferred styles');
    }

    // add deferred style event listener
    /*var raf = requestAnimationFrame || mozRequestAnimationFrame ||
        webkitRequestAnimationFrame || msRequestAnimationFrame;
    if (raf) raf(function() { window.setTimeout(loadDeferredStyles, 0); });
    else window.addEventListener('load', loadDeferredStyles);*/

    document.addEventListener('DOMContentLoaded', afterLoadEvent);

    setTimeout(function(){
        (!documentLoaded) && afterLoadEvent() // this will only run if the document has not been loaded yet
    }, 500);
})(document, window);